Added sessionPreset to change camera quality in CaptureSettings for ios only
shogo4405/HaishinKit.dart pull request #31
Opened 2023-05-25 06:28 UTC by tian-zhihui

## Description & motivation
Add sessionPreset in CaptureSettings.
- [x] sessionPreset **(default is AVCaptureSessionPreset.medium)**

You can find all available value from the url below.
https://developer.apple.com/documentation/avfoundation/avcapturesession/preset

## Type of change
Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## Screenshots:

```
stream.captureSettings = CaptureSettings(
    sessionPreset: AVCaptureSessionPreset.photo,
);
```

2023-05-26 00:04 UTC, tian-zhihui commented on lib/capture_settings.dart
> +      sessionPreset: AVCaptureSessionPreset.values.byName(map['continuousExposure'] as String),
😅😅😅
失礼致しました。コピペミスでした。
修正いたします。

2023-05-26 00:05 UTC, tian-zhihui commented on ios/Classes/RTMPStreamHandler.swift
> +                        instance?.videoSettings[.profileLevel] = kVTProfileLevel_H264_High_AutoLevel
おっしゃるとおりです。
取り出して別設定にします。

2023-05-26 01:42 UTC, tian-zhihui commented on lib/capture_settings.dart
> +      sessionPreset: AVCaptureSessionPreset.values.byName(map['continuousExposure'] as String),
修正しました。
https://github.com/shogo4405/HaishinKit.dart/pull/31/commits/79f39387195826a6eeeaa9f1841ff4df6044046e

2023-05-26 01:42 UTC, tian-zhihui commented on ios/Classes/RTMPStreamHandler.swift
> +                        instance?.videoSettings[.profileLevel] = kVTProfileLevel_H264_High_AutoLevel
修正しました。
https://github.com/shogo4405/HaishinKit.dart/pull/31/commits/aa4c750895264b068171d084716b30ec75cd4dcc

2023-05-26 03:47 UTC, shogo4405 requested changes

2023-05-26 03:47 UTC, shogo4405 commented on lib/video_settings.dart
> +  kVTProfileLevel_H263_Profile3_Level45('kVTProfileLevel_H263_Profile3_Level45'),
[MUST]
こういう風に定義してあるとライブラリー利用者側からは、利用可能なのかな？って思われます。現在、そもそも利用不可能なので定義しないほうがよいでしょう。
- 現状、H264のみの対応になります。

2023-05-26 04:07 UTC, shogo4405 commented
sessionPresetについては受け入れ可能なためprofileLevelは別のPRにするとスムーズです。
せっかくのクロスプラットフォームなので、ProfileLevelについてはAndroid側も対応したいため。次の設計であれば受け入れ可能です。
**Dart**
```
enum ProfileLevel {
  H264_Baseline_3_0(“H264_Baseline_3_0”),
  H264_Baseline_3_1(“H264_Baseline_3_1”),
  ….
}
```
**Swift**
```
enum ProfileLevel: String {
   case H264_Baseline_3_0 = “H264_Baseline_3_0”
   case H264_Baseline_3_1 = “H264_Baseline_3_1”
   …

   var kVTProfileLevel: CFString {
       switch self {
          case .H264_Baseline_3_0:
              return kVTProfileLevel_H264_Baseline_3_0
          case .H264_Baseline_3_1:
              return kVTProfileLevel_H264_Baseline_3_1
       }
   }
}
```
**Kotlin**
```
enum class ProfileLevel(val rawValue: String, val profile: int, val level: Int) {
    H264Baseline30(“H264_Baseline_3_0”, AVCProfileBaseline, AVCLevel30)
    …
}
```

2023-05-26 10:43 UTC, tian-zhihui commented
@shogo4405 
アドバイスを頂きありがとうございます。
上記の内容もついでに実装たいと考えていますが、
Android側がサポートしているProfileLevelは下記の部分でしょうか？
https://github.com/shogo4405/HaishinKit.kt/blob/67aa810a0f8c42370efab7f349300e4e2704c4a4/haishinkit/src/main/java/com/haishinkit/codec/VideoCodec.kt#L187
つまり下記の11種類だという認識でよろしいでしょうか？
1. MediaCodecInfo.CodecProfileLevel.AVCProfileBaseline
2. MediaCodecInfo.CodecProfileLevel.AVCProfileMain
3. MediaCodecInfo.CodecProfileLevel.AVCProfileHigh
4. MediaCodecInfo.CodecProfileLevel.AVCLevel31
5. MediaCodecInfo.CodecProfileLevel.AVCLevel32
6. MediaCodecInfo.CodecProfileLevel.AVCLevel4
7. MediaCodecInfo.CodecProfileLevel.AVCLevel41
8. MediaCodecInfo.CodecProfileLevel.AVCLevel42
9. MediaCodecInfo.CodecProfileLevel.AVCLevel5
10. MediaCodecInfo.CodecProfileLevel.AVCLevel51
11. MediaCodecInfo.CodecProfileLevel.AVCLevel52

2023-05-26 11:25 UTC, shogo4405 commented
1. MediaCodecInfo.CodecProfileLevel.AVCProfileBaseline
2. MediaCodecInfo.CodecProfileLevel.AVCProfileMain
3. MediaCodecInfo.CodecProfileLevel.AVCProfileHigh

と、つぎの組み合わせになります。

1. MediaCodecInfo.CodecProfileLevel.AVCLevel31
2. MediaCodecInfo.CodecProfileLevel.AVCLevel32
3. MediaCodecInfo.CodecProfileLevel.AVCLevel4
4. MediaCodecInfo.CodecProfileLevel.AVCLevel41
5. MediaCodecInfo.CodecProfileLevel.AVCLevel42
6. MediaCodecInfo.CodecProfileLevel.AVCLevel5
7. MediaCodecInfo.CodecProfileLevel.AVCLevel51
8. MediaCodecInfo.CodecProfileLevel.AVCLevel52

したがって3x8=24種類になると思います。

2023-05-29 04:38 UTC, tian-zhihui commented
ありがとうございます。
指摘に合わせて修正いたしました。
お手数ですが、ご確認お願い致します。

2023-05-30 10:48 UTC, shogo4405 approved these changes

2023-05-30 10:51 UTC, shogo4405 commented
ありがとうございました！

2023-05-30 10:51 UTC, merged